import "docobj.idl";

// MTDev.idl : IDL source for MTDev
//

// This file will be processed by the MIDL tool to
// produce the type library (MTDev.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#line 24 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IApplication;
interface IParser;
[
	object,
	uuid(C7242A99-D06C-4A9E-818D-5D3180EB8D90),
	dual,
	oleautomation,
	helpstring("IDocument Interface"),
	pointer_default(unique)
] 
#line 36 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IDocument : IDispatch {
#line 38 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method Save")] HRESULT  Save();
	[id(2),helpstring("method Close")] HRESULT  Close();
#line 41 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(10),helpstring("property Application")] HRESULT  Application([out,retval] IApplication **pVal );
	[propget,id(11),helpstring("property Modified")] HRESULT  Modified([out,retval] VARIANT_BOOL *pVal);
	[propput,id(11),helpstring("property Modified")] HRESULT  Modified([in] VARIANT_BOOL newVal);
	[propget,id(12),helpstring("property Path")] HRESULT  Path([out,retval] BSTR *pVal );
};

[
	object,
	uuid(4FE902DC-9597-4d4e-81EC-179AFADCF8F7),
	dual,
	oleautomation,
	helpstring("ISourceDocument Interface"),
	pointer_default(unique)
] 
#line 56 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface ISourceDocument : IDocument {
};

[
	object,
	uuid(C7242A99-D06C-4A9E-818D-5D3180EB8D99),
	dual,
	oleautomation,
	helpstring("IProjectDocument Interface"),
	pointer_default(unique)
] 
#line 69 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IProjectDocument : IDocument {
#line 71 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(20),helpstring("method SaveAll")] HRESULT  SaveAll([out,retval] VARIANT_BOOL *Result);
	[id(21),helpstring("method Build")] HRESULT  Build([out,retval] VARIANT_BOOL *Result);
	[id(22),helpstring("method Run")] HRESULT  Run([out] LONG *ExitCode, [out,retval] VARIANT_BOOL *Result);
	[id(23),helpstring("method Clean")] HRESULT  Clean();
#line 76 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(24),helpstring("method AddFile")] HRESULT  AddFile([in] BSTR FilePath, [out,retval] VARIANT_BOOL *Result);
	[id(25),helpstring("method RemoveFile")] HRESULT  RemoveFile([in] BSTR FilePath, [out,retval] VARIANT_BOOL *Result);
#line 79 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(26),helpstring("method GetFileFirst")] HRESULT  GetFileFirst([out] BSTR *FileName , [out,retval] VARIANT_BOOL *Result);
	[id(27),helpstring("method GetFileNext")] HRESULT  GetFileNext([out] BSTR *FileName , [out,retval] VARIANT_BOOL *Result);
#line 82 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(41),helpstring("property Active")] HRESULT  Active([out,retval] VARIANT_BOOL *pVal);
	[propput,id(41),helpstring("property Active")] HRESULT  Active([in] VARIANT_BOOL newVal);
#line 85 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(42),helpstring("property TargetPath")] HRESULT  TargetPath([out,retval] BSTR *pVal );
	[propget,id(43),helpstring("property TargetDirectory")] HRESULT  TargetDirectory([out,retval] BSTR *pVal );
#line 88 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(44),helpstring("property Notes")] HRESULT  Notes([out,retval] BSTR *pVal );
	[propput,id(44),helpstring("property Notes")] HRESULT  Notes([in] BSTR newVal);
#line 91 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(45),helpstring("property Params")] HRESULT  Params([out,retval] BSTR *pVal );
	[propput,id(45),helpstring("property Params")] HRESULT  Params([in] BSTR newVal);
#line 94 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(46),helpstring("property Switches")] HRESULT  Switches([out,retval] BSTR *pVal );
	[propput,id(46),helpstring("property Switches")] HRESULT  Switches([in] BSTR newVal);
#line 97 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(47),helpstring("property LangGens")] HRESULT  LangGens([out,retval] BSTR *pVal );
	[propput,id(47),helpstring("property LangGens")] HRESULT  LangGens([in] BSTR newVal);
};

[
	object,
	uuid(EE3E904C-6AA0-401A-BCB5-A936E3B717F6),
	dual,
	oleautomation,
	helpstring("IApplication Interface"),
	pointer_default(unique)
] 
#line 111 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IApplication : IDispatch {
#line 113 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method Quit")] HRESULT  Quit([in] VARIANT_BOOL SaveChanges);
	[id(2),helpstring("method ScreenRefresh")] HRESULT  ScreenRefresh();
	[id(3),helpstring("method Resize")] HRESULT  Resize([in] LONG Width, [in] LONG Height);
	[id(4),helpstring("method Activate")] HRESULT  Activate();
	[id(5),helpstring("method OpenDocument")] HRESULT  OpenDocument([in] BSTR Path, [out,retval] IDocument **pDoc );
	[id(6),helpstring("method FindDocument")] HRESULT  FindDocument([in] BSTR Path, [out,retval] IDocument **pDoc );
	[id(7),helpstring("method CreateProject")] HRESULT  CreateProject([in] BSTR Path, [out,retval] IProjectDocument **pDoc );
#line 121 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(17),helpstring("property ProjectCount")] HRESULT  ProjectCount([out,retval] LONG *pVal);
	[propget,id(18),helpstring("property Projects")] HRESULT  Projects([in] LONG nIndex, [out,retval] IProjectDocument **pDoc );
	[propget,id(19),helpstring("property ActiveProject")] HRESULT  ActiveProject([out,retval] IProjectDocument **pVal );
#line 125 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(30),helpstring("property MRUDocument")] HRESULT  MRUDocument([out,retval] BSTR *pVal );
	[propget,id(31),helpstring("property Visible")] HRESULT  Visible([out,retval] VARIANT_BOOL *pVal);
	[propput,id(31),helpstring("property Visible")] HRESULT  Visible([in] VARIANT_BOOL newVal);
	[propget,id(33),helpstring("property Parser")] HRESULT  Parser([out,retval] IParser **pVal );
};

[
	uuid(0971D8E9-34A6-4846-81F3-B7E8FE27B9A3)
] 
#line 135 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
enum GrammaticalSymbolClass {
	gscUndefined = 0,
	gscTerminal = 1,
	gscNonTerminal = 2,
	gscStdTerminal = 3,
};

[
	uuid(6BE132AD-00C5-4afd-ABDB-32F1D0C013D3)
] 
#line 141 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
enum GrammaticalSymbolKind {
	gskUndefined = 0,
	gskNormal = 1,
	gskOptional = 2,
	gskChildOptional = 3,
};

[
	object,
	uuid(B0E9D7B9-ECC5-44bd-8F18-BD3499B73DC2),
	dual,
	helpstring("IGrammaticalSymbol Interface"),
	pointer_default(unique)
] 
#line 152 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IGrammaticalSymbol : IDispatch {
#line 154 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(1),helpstring("property Name")] HRESULT  Name([out,retval] BSTR *pVal );
	[propput,id(1),helpstring("property Name")] HRESULT  Name([in] BSTR newVal);
	[propget,id(2),helpstring("property Class")] HRESULT  Class([out,retval] enum GrammaticalSymbolClass *pVal);
	[propput,id(2),helpstring("property Class")] HRESULT  Class([in] enum GrammaticalSymbolClass newVal);
	[propget,id(3),helpstring("property Kind")] HRESULT  Kind([out,retval] enum GrammaticalSymbolKind *pVal);
	[propput,id(3),helpstring("property Kind")] HRESULT  Kind([in] enum GrammaticalSymbolKind newVal);
	[propget,id(4),helpstring("property Actions")] HRESULT  Actions([out,retval] BSTR *pVal );
	[propput,id(4),helpstring("property Actions")] HRESULT  Actions([in] BSTR newVal);
};

[
	object,
	uuid(6AF2BCFC-CCFF-40a2-83C6-8AD725EAE48A),
	dual,
	helpstring("IGrammaticalVariant Interface"),
	pointer_default(unique)
] 
#line 173 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IGrammaticalVariant : IDispatch {
#line 175 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method AddSymbol")] HRESULT  AddSymbol([out,retval] IGrammaticalSymbol **pSymbol );
#line 177 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(10),helpstring("property Actions")] HRESULT  Actions([out,retval] BSTR *pVal );
	[propput,id(10),helpstring("property Actions")] HRESULT  Actions([in] BSTR newVal);
};

[
	object,
	uuid(092C0FB9-67A7-4C8A-9C6E-F125CD40C498),
	dual,
	helpstring("IGrammaticalRule Interface"),
	pointer_default(unique)
] 
#line 190 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IGrammaticalRule : IDispatch {
#line 192 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method AddVariant")] HRESULT  AddVariant([out,retval] IGrammaticalVariant **pVariant );
	[id(2),helpstring("method AssembleText")] HRESULT  AssembleText([out,retval] BSTR *aText );
#line 195 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(10),helpstring("property Name")] HRESULT  Name([out,retval] BSTR *pVal );
	[propput,id(10),helpstring("property Name")] HRESULT  Name([in] BSTR newVal);
	[propget,id(11),helpstring("property Actions")] HRESULT  Actions([out,retval] BSTR *pVal );
	[propput,id(11),helpstring("property Actions")] HRESULT  Actions([in] BSTR newVal);
};

[
	object,
	uuid(F27BAF30-1371-49f6-B12D-ADCA02C94E05),
	dual,
	helpstring("IGrammar Interface"),
	pointer_default(unique)
] 
#line 210 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IGrammar : IDispatch {
#line 212 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method AddRule")] HRESULT  AddRule([out,retval] IGrammaticalRule **pVariant );
	[id(2),helpstring("method AssembleText")] HRESULT  AssembleText([out,retval] BSTR *aText );
#line 215 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[propget,id(10),helpstring("property RuleCount")] HRESULT  RuleCount([out,retval] LONG *pVal);
	[propget,id(11),helpstring("property Rules")] HRESULT  Rules([in] LONG nIndex, [out,retval] IGrammaticalRule **pVal );
};

[
	object,
	uuid(763009C4-1A1B-4185-96A6-2BFAEF106F0D),
	dual,
	helpstring("IParser Interface"),
	pointer_default(unique)
] 
#line 228 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
interface IParser : IDispatch {
#line 230 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(1),helpstring("method CreateRule")] HRESULT  CreateRule([out,retval] IGrammaticalRule **aRule );
	[id(2),helpstring("method CreateGrammar")] HRESULT  CreateGrammar([out,retval] IGrammar **aGrammar );
#line 233 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(3),helpstring("method Parse")] HRESULT  Parse([in] BSTR pText, [out,retval] IGrammar **aGrammar );
#line 237 "x:\\multitranslator\\sources\\mtdev\\com\\cominterfaces.h"
	[id(4),helpstring("method ComposeMainFunction")] HRESULT  ComposeMainFunction([in] BSTR RootRule, [in] VARIANT_BOOL IgnoreCase, [in]BSTR IgnorePairList, [in]BSTR ReplacePairList, [out,retval] BSTR *pText );
};


[ version(1.0), uuid(B5708153-CD7A-416D-9022-D46E486C53F0), helpstring("MultiTranslator IDE Type Library") ]
library mtdev
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");


	importlib("stdole2.tlb");
	[
		version(1.0),
		uuid(0217A734-4550-4CD9-A8A2-F6066E201640),
		helpstring("Parser Class")
	] 
#line 155 "x:\\multitranslator\\sources\\mtdev\\com\\comparser.h"
	coclass Parser {
		interface IParser;
	};

	[
		version(1.0),
		uuid(206DDA10-728E-4C72-81CC-36FB3BE80916),
		helpstring("ProjectDocument Class")
	] 
#line 38 "x:\\multitranslator\\sources\\mtdev\\com\\comprojectdocument.h"
	coclass ProjectDocument {
		interface IProjectDocument;
		interface IDocument;
	};

	[
		version(1.0),
		uuid(0314E4F6-E6C5-4773-84D4-B71E8945851B),
		helpstring("SourceDocument Class")
	] 
#line 39 "x:\\multitranslator\\sources\\mtdev\\com\\comsourcedocument.h"
	coclass SourceDocument {
		interface ISourceDocument;
		interface IDocument;
	};

	[
		version(1.0),
		uuid(ADC6D969-C5D5-49E4-A75C-F58156BDDBC9),
		helpstring("Application Class")
	] 
#line 30 "x:\\multitranslator\\sources\\mtdev\\com\\comapplication.h"
	coclass Application {
		interface IApplication;
	};

}

;
