//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MTDev.rc
//
#define IDR_MANIFEST                    1
#define IDB_CHECK                       100
#define IDB_CLASS_VIEW                  101
#define ID_HELP_HELP                    101
#define IDB_DEBUG_VIEW                  102
#define ID_HELP_HELP102                 102
#define IDB_FILE_VIEW                   103
#define IDB_LIGHTBULB                   104
#define IDB_LOGO                        105
#define IDB_RESOURCE_VIEW               107
#define IDR_F_MAIN_TMPL1                107
#define IDB_STATISTIC                   109
#define IDB_WORKSPACE                   110
#define IDR_MAINFRAME                   111
#define IDR_DOC_PROJECT                 112
#define IDR_DOC_SOURCE                  113
#define IDR_APPLICATION                 114
#define IDI_ITEM_DELETE_ICON            115
#define IDI_ITEM_EDIT_ICON              116
#define IDI_ITEM_MOVEDOWN_ICON          117
#define IDI_ITEM_MOVEUP_ICON            118
#define IDI_ITEM_MOVE_ICON              119
#define IDI_ITEM_NEW_ICON               120
#define IDI_PROJECT_EMPTY               121
#define IDI_PROJECT_SIMPLE              122
#define IDI_SYNTAX_DIAGRAMS             123
#define IDC_ADD_TO_VARIANT              200
#define IDC_ADD_VARIANT                 201
#define IDC_BACKGRND                    202
#define IDC_BUTTON_OPTIMIZE             204
#define IDC_CHECK_LOOK_IN_SUBFOLDERS    208
#define IDC_CHECK_MATCH_CASE            209
#define IDC_CHECK_OPTIONAL              211
#define IDC_CHECK_REGEXP                212
#define IDC_CHECK_WHOLE_WORD            213
#define IDC_CHECK_WRAP_AROUND           214
#define IDC_COMBO_FILE_TYPES            215
#define IDC_COMBO_FIND                  216
#define IDC_COMBO_LOOK_IN               217
#define IDC_COMBO_MODULES               218
#define IDC_COMBO_PLACE_RULES           219
#define IDC_COMBO_REPLACE               220
#define IDC_COPYRIGHT                   221
#define IDC_DELETE_TERMS                222
#define IDC_EDIT3                       224
#define IDC_EDIT_ITEM                   225
#define IDC_EDIT_ITEM_NAME              226
#define IDC_EDIT_LOCATION               227
#define IDC_FIND                        229
#define IDC_GOTOLINE_CURRENT_LINE       230
#define IDC_GOTOLINE_GOTOLINE           231
#define IDC_GOTOLINE_LAST_LINE          232
#define IDC_IS_TERM                     233
#define IDC_IS_UNTERM                   234
#define IDC_LIST1                       237
#define IDC_LIST2                       238
#define IDC_LIST_MESSAGES               239
#define IDC_LOGO                        240
#define IDC_LV_DOCUMENTS                241
#define IDC_MAIL                        245
#define IDC_MARGIN                      246
#define IDC_URL                         246
#define IDC_MOVE_TERM_DOWN              247
#define IDC_MOVE_TERM_UP                248
#define IDC_NEW_TERM                    249
#define IDC_NEXTTIP                     250
#define IDC_OPTIMIZE_PROGRESS           251
#define IDC_OUTPUTSCREEN                252
#define IDC_RADIO_DIR_UP                264
#define IDC_RADIO_SCOPE_GLOBAL          265
#define IDC_RADIO_SCOPE_SELECTION       266
#define IDC_REPLACE                     267
#define IDC_REPLACE_ALL                 268
#define IDC_RULE_NAME                   269
#define IDC_STARTUP                     271
#define IDC_STATIC_ERROR                272
#define IDC_TIPSTRING                   274
#define IDC_TREE                        275
#define IDC_TREE1                       276
#define IDC_TREE_RULES                  277
#define IDC_TREE_RULES_OPT              278
#define IDC_VAR_TAB                     279
#define IDC_VERSION                     280
#define IDD_ABOUTBOX                    500
#define IDD_ADD_RULE                    501
#define IDD_FIND                        502
#define IDD_FIND_IN_FILES               503
#define IDD_GOTOLINE                    504
#define IDD_OUTPUT                      507
#define IDD_REPLACE                     509
#define IDD_STATISTIC                   510
#define IDD_TIP                         512
#define IDP_OLE_INIT_FAILED             1000
#define IDR_BUILD                       1005
#define IDR_CONTEXT_MENU                1006
#define IDR_DEBUG                       1007
#define IDR_EDIT                        1008
#define IDR_FULLSCREEN                  1009
#define IDR_ADD_RULE                    1010
#define IDR_MENU_ARGS                   1013
#define IDR_MENU_DIRS                   1014
#define IDR_MENU_IMAGES                 1015
#define IDR_MTDEV                       1016
#define IDR_POPUP_BREAKPOINTS           1017
#define IDR_POPUP_CLW_BASE              1018
#define IDR_POPUP_CLW_FUNCS             1019
#define IDR_POPUP_CLW_PROJECT           1020
#define IDR_POPUP_CLW_RECENTLY_RULES    1021
#define IDR_POPUP_CLW_RULE              1022
#define IDR_POPUP_CLW_RULES             1023
#define IDR_POPUP_CLW_RULES_RECENTLY    1024
#define IDR_POPUP_CLW_STRUCTS           1025
#define IDR_POPUP_CLW_USER_FOLDER       1026
#define IDR_POPUP_CLW_VARIANT           1027
#define IDR_POPUP_DOC_SOURCE            1028
#define IDR_POPUP_DOC_SOURCE_MARGIN     1029
#define IDR_POPUP_FLW_BASE              1030
#define IDR_POPUP_FLW_PROJECT           1031
#define IDR_POPUP_FLW_SOURCE            1032
#define IDR_POPUP_FLW_SOURCES           1033
#define IDR_POPUP_MAIN_AREA             1034
#define IDR_POPUP_MDI_TABS              1035
#define IDR_POPUP_OUTPUT                1036
#define IDR_POPUP_OUTPUT_SCREEN         1037
#define IDR_POPUP_TOOLBAR               1038
#define IDR_UNDO                        1039
#define IDS_AUTOMATION_SERVER_CLOSING   5000
#define IDS_BUILD_TOOLBAR               5001
#define IDS_CANT_CREATE_DIR_s           5002
#define IDS_CANT_CREATE_FILE_s          5003
#define IDS_CANT_DELETE_FILE_s          5004
#define IDS_CANT_EXECUTE_ss             5005
#define IDS_CANT_FIND_FILE_s            5006
#define IDS_CANT_FIND_GENERATOR_s       5007
#define IDS_CANT_LOAD_EDITOR            5008
#define IDS_CANT_LOAD_INSTALLED_FILE_s  5009
#define IDS_CANT_READ_FILE_s            5010
#define IDS_CANT_WRITE_TO_FILE_s        5011
#define IDS_CLOSE_APP_BUILD_IN_PROGRESS 5012
#define IDS_CLOSE_APP_DEBUG_IN_PROGRESS 5013
#define IDS_CLOSE_PROJECT_BUILD_IN_PROGRESS 5014
#define IDS_CLOSE_PROJECT_DEBUG_IN_PROGRESS 5015
#define IDS_CLW_FUNCS_TITLE             5016
#define IDS_CLW_RECENTLY_TITLE          5017
#define IDS_CLW_RULES_TITLE             5018
#define IDS_CLW_STRUCTS_TITLE           5019
#define IDS_CUSTOMIZE                   5020
#define IDS_DEBUG_TOOLBAR               5021
#define IDS_DO_YOU_WANT_DELETE_FILE_s   5022
#define IDS_DUMMY_UNDO_ACTION           5023
#define IDS_EDIT_TOOLBAR                5024
#define IDS_FILE_ALREADY_EXISTS_s       5025
#define IDS_FILE_CHANGED_OUTSIDE_s      5026
#define IDS_FILE_CORRUPTED_s            5027
#define IDS_FILE_TREE_OTHER_DOC_FOLDER  5028
#define IDS_FILE_TREE_SOURCE_FOLDER     5029
#define IDS_MAIN_TOOLBAR                5030
#define IDS_NEW_FOLDER_d                5031
#define IDS_NO_MODULE_NAME              5032
#define IDS_NO_RULE_NAME                5033
#define IDS_NO_STATISTIC_FILE           5034
#define IDS_OBJECT_HAS_NOT_PROPS        5035
#define IDS_PARSE_REPORT_TO_FILE_s      5036
#define IDS_PARSE_REPORT_WILL_TO_FILE_s 5037
#define IDS_PROJECT_ADD_FILES           5038
#define IDS_PROJECT_FILE_BAD_s          5039
#define IDS_PROJECT_WAS_CHANGED_s       5040
#define IDS_PROJECT_WZD_DEF_TITLE       5041
#define IDS_PROJECT_WZD_SIMPLE_TITLE    5042
#define IDS_CANT_PERFORM_OPERATION_s    5043
#define IDS_FILE_IS_READ_ONLY_s         5044
#define IDS_RUN_PROJECT_NO_MODULE_s     5045
#define IDS_RUN_PROJECT_WAS_CHANGED_s   5046
#define IDS_SOURCE_WAS_CHANGED_s        5047
#define IDS_STRING_NOT_FOUND_FMT        5048
#define IDS_TOD_DID_YOU_KNOW            5049
#define IDS_TOD_FILENAME                5050
#define IDS_TOD_FILE_ABSENT             5051
#define IDS_TOD_FILE_CORRUPT            5052
#define IDS_CANT_REMOVE_WRITE_PROTECTION_s 5053
#define IDS_AUTOSAVE_COMPLETED          5054
#define IDS_FILE_SAVING_s               5055
#define IDS_FILE_LOADING_s              5056
#define IDS_CODEGENERATOR_CAUSED_ERROR_ss 5057
#define IDS_CANT_SAVE_DOC_BECAUSE_SAME_EXISTS_s 5058
#define IDS_PROJECT_FILE_ALREADY_EXISTS_s 5059
#define ID_BREAKPOINTS_CLEAR_ALL        8000
#define ID_BREAKPOINTS_DELETE           8001
#define ID_BREAKPOINTS_DISABLE          8002
#define ID_BREAKPOINTS_DISABLE_ALL      8003
#define ID_BREAKPOINTS_ENABLE_ALL       8004
#define ID_BREAKPOINTS_GOTO             8005
#define ID_BUILD_BUILD_PROJECT          8007
#define ID_BUILD_CLEAN                  8008
#define ID_BUILD_COMPILE_SOURCE         8009
#define ID_BUILD_NEXT_ERROR             8010
#define ID_BUILD_PREV_ERROR             8011
#define ID_BUILD_STOP_BUILD             8012
#define ID_CLW_CLEAR_RECENTLY_LIST      8014
#define ID_CLW_DEFINITION               8015
#define ID_CLW_DELETE                   8016
#define ID_CLW_MOVETOTOP                8017
#define ID_CLW_NEW_FOLDER               8018
#define ID_CLW_RENAME                   8019
#define ID_CLW_SORT                     8020
#define ID_DEBUG_DISABLE_BREAKPOINT     8021
#define ID_DEBUG_NEW_BREAKPOINT         8022
#define ID_DEBUG_PAUSE                  8023
#define ID_DEBUG_PAUSE_ON_PARSE         8024
#define ID_DEBUG_START_DEBUG            8025
#define ID_DEBUG_START_RUN              8026
#define ID_DEBUG_STEPINTO               8027
#define ID_DEBUG_STEPOVER               8028
#define ID_DEBUG_STOP                   8029
#define ID_DEBUG_TOGGLE_BREAKPOINT      8030
#define ID_DUMMY_CLEAN                  8031
#define ID_DUMMY_GOTO                   8032
#define ID_DUMMY_INSERT                 8033
#define ID_DUMMY_REBUILD_ALL            8034
#define ID_DUMMY_STOP_BUILD             8035
#define ID_EDIT_AUTOFORMAT              8036
#define ID_EDIT_CLEAR_BOOKMARKS         8037
#define ID_EDIT_COMPLETE_WORD           8038
#define ID_EDIT_DECREASE_LINE_INDENT    8039
#define ID_EDIT_FIND_DECLARATION        8040
#define ID_EDIT_FIND_IN_FILES           8041
#define ID_EDIT_FIND_NEXT               8042
#define ID_EDIT_FOLD_ALL                8043
#define ID_EDIT_FOLD_CUR                8044
#define ID_EDIT_GOTOLINE                8045
#define ID_EDIT_INCREASE_LINE_INDENT    8046
#define ID_EDIT_LOWERCASE               8047
#define ID_EDIT_NEXT_BOOKMARK           8048
#define ID_EDIT_PREV_BOOKMARK           8049
#define ID_EDIT_SYNC_EXPLORER           8050
#define ID_EDIT_TABIFYSELECTION         8051
#define ID_EDIT_TOGGLE_BOOKMARK         8052
#define ID_EDIT_UNDO_DUMMY              8053
#define ID_EDIT_UNFOLD_ALL              8054
#define ID_EDIT_UNFOLD_CUR              8055
#define ID_EDIT_UNTABIFYSELECTION       8056
#define ID_EDIT_UPPERCASE               8057
#define ID_EDIT_ZOOM_IN                 8058
#define ID_EDIT_ZOOM_OUT                8059
#define ID_EDIT_ZOOM_RESET              8060
#define ID_FILE_CLOSE_ALL               8061
#define ID_FILE_MRU_PROJECT1            8062
#define ID_FILE_MRU_PROJECT10           8063
#define ID_FILE_MRU_PROJECT11           8064
#define ID_FILE_MRU_PROJECT12           8065
#define ID_FILE_MRU_PROJECT13           8066
#define ID_FILE_MRU_PROJECT14           8067
#define ID_FILE_MRU_PROJECT15           8068
#define ID_FILE_MRU_PROJECT16           8069
#define ID_FILE_MRU_PROJECT2            8070
#define ID_FILE_MRU_PROJECT3            8071
#define ID_FILE_MRU_PROJECT4            8072
#define ID_FILE_MRU_PROJECT5            8073
#define ID_FILE_MRU_PROJECT6            8074
#define ID_FILE_MRU_PROJECT7            8075
#define ID_FILE_MRU_PROJECT8            8076
#define ID_FILE_MRU_PROJECT9            8077
#define ID_FILE_NEW_DOC1                8078
#define ID_FILE_NEW_DOC10               8079
#define ID_FILE_NEW_DOC11               8080
#define ID_FILE_NEW_DOC12               8081
#define ID_FILE_NEW_DOC13               8082
#define ID_FILE_NEW_DOC14               8083
#define ID_FILE_NEW_DOC15               8084
#define ID_FILE_NEW_DOC16               8085
#define ID_FILE_NEW_DOC2                8086
#define ID_FILE_NEW_DOC3                8087
#define ID_FILE_NEW_DOC4                8088
#define ID_FILE_NEW_DOC5                8089
#define ID_FILE_NEW_DOC6                8090
#define ID_FILE_NEW_DOC7                8091
#define ID_FILE_NEW_DOC8                8092
#define ID_FILE_NEW_DOC9                8093
#define ID_FILE_PROJECT_CLOSE           8094
#define ID_FILE_PROJECT_OPEN            8095
#define ID_FILE_PROJECT_SAVE            8096
#define ID_FILE_SAVE_ALL                8097
#define ID_HELP_KEYBOARDMAP             8098
#define ID_HELP_TIP_OF_THE_DAY          8099
#define ID_INDEPENDENT_BAR_BREAKPOINTS  8100
#define ID_INDEPENDENT_BAR_SCREEN       8101
#define ID_INDICATOR_POS                8102
#define ID_MDITABS_BOTTOM               8103
#define ID_MDITABS_CLOSE                8104
#define ID_MDITABS_ICONS                8105
#define ID_MDITABS_TOP                  8106
#define ID_MENU_DIR1                    8107
#define ID_MENU_DIR2                    8108
#define ID_MENU_DIR3                    8109
#define ID_MENU_ITEM1                   8110
#define ID_MENU_ITEM2                   8111
#define ID_MENU_ITEM3                   8112
#define ID_NEW_ACCELERATOR              8113
#define ID_NEW_BITMAP                   8114
#define ID_NEW_CURSOR                   8115
#define ID_NEW_DIALOG                   8116
#define ID_NEW_ICON                     8117
#define ID_NEW_MENU                     8118
#define ID_NEW_STRING_TABLE             8119
#define ID_NEW_TOOLBAR                  8120
#define ID_NEW_VERSION                  8121
#define ID_OPTIONS_SAVETOFILE           8122
#define ID_OPTIONS_SELECTALL            8123
#define ID_OUTPUT_GOTO_ERROR            8124
#define ID_OUTPUT_OPTIONS_ALTCONVERSION 8125
#define ID_OUTPUT_OPTIONS_AUTOCLEAR     8126
#define ID_OUTPUT_OPTIONS_AUTOCLOSE     8127
#define ID_OUTPUT_OPTIONS_BACKCOLOR     8128
#define ID_OUTPUT_OPTIONS_CLEAR         8129
#define ID_OUTPUT_OPTIONS_OEM           8130
#define ID_OUTPUT_OPTIONS_SIZETOCONTENT 8131
#define ID_OUTPUT_OPTIONS_TEXTCOLOR     8132
#define ID_PARSING_COMPLETE_REPORT      8133
#define ID_PARSING_REPORT_TO_FILE       8134
#define ID_PARSING_SHORT_REPORT         8135
#define ID_POPUP_PROJECT_SET_ACTIVE     8136
#define ID_PROJECT_ADD_CODE_TEMPLATE    8137
#define ID_PROJECT_ADD_FILES            8138
#define ID_PROJECT_ADD_RULE             8139
#define ID_PROJECT_ADD_TO_KNOWLEDGEBASE 8140
#define ID_PROJECT_BUILD                8141
#define ID_PROJECT_BUILD_SYNTAX_DIAGRAM 8142
#define ID_PROJECT_BUILD_SYNTAX_TREE    8143
#define ID_PROJECT_EXPORT_TO_XBNF       8144
#define ID_TOOLS_IMPORT_GRAMMAR         8145
#define ID_PROJECT_NEW_FILE             8146
#define ID_PROJECT_SETTINGS             8147
#define ID_PROJECT_SET_ACTIVE           8148
#define ID_PROJECT_UNLOAD               8149
#define ID_PROPERTIES                   8150
#define ID_RESOURCE_OPEN                8151
#define ID_RESOURCE_OPEN_BINARY         8152
#define ID_SOURCE_FILE_COMPILE          8153
#define ID_SOURCE_FILE_PHYS_DELETE      8154
#define ID_SOURCE_FILE_RECREATE         8155
#define ID_SOURCE_FILE_REMOVE           8156
//#define ID_TOOLS_BUILDSYNTAXTREE        8157
#define ID_TOOLS_ENTRY                  8158
#define ID_TOOLS_GRAMMATICAL_INFERENCE  8159
#define ID_TOOLS_MACRO                  8160
#define ID_TOOLS_STATISTIC              8161
#define ID_TOOLS_SYNTAX_DIAGRAMS        8162
#define ID_TOOLS_VIEW_LIBRARIES         8163
#define ID_USER_TOOL1                   8164
#define ID_USER_TOOL10                  8165
#define ID_USER_TOOL2                   8166
#define ID_USER_TOOL3                   8167
#define ID_USER_TOOL4                   8168
#define ID_USER_TOOL5                   8169
#define ID_USER_TOOL6                   8170
#define ID_USER_TOOL7                   8171
#define ID_USER_TOOL8                   8172
#define ID_USER_TOOL9                   8173
#define ID_VIEW_BREAKPOINTS             8174
#define ID_VIEW_BUILD_TOOLBAR           8175
#define ID_VIEW_CUSTOMIZE               8176
#define ID_VIEW_DEBUG_TOOLBAR           8177
#define ID_VIEW_DOCUMENT_TAB            8178
#define ID_VIEW_EDIT_TOOLBAR            8179
#define ID_VIEW_FOLD_MARGIN             8180
#define ID_VIEW_FULLSCREEN              8181
#define ID_VIEW_INDENTGUIDES            8182
#define ID_VIEW_INFOBAR                 8183
#define ID_VIEW_MDI_TABS                8184
#define ID_VIEW_OUTPUT                  8185
#define ID_VIEW_SCREEN                  8186
#define ID_VIEW_TOOLBARS                8187
#define ID_VIEW_USER_TOOLBAR1           8188
#define ID_VIEW_USER_TOOLBAR2           8189
#define ID_VIEW_USER_TOOLBAR3           8190
#define ID_VIEW_USER_TOOLBAR4           8191
#define ID_VIEW_USER_TOOLBAR5           8192
#define ID_VIEW_USER_TOOLBAR6           8193
#define ID_VIEW_USER_TOOLBAR7           8194
#define ID_VIEW_USER_TOOLBAR8           8195
#define ID_VIEW_USER_TOOLBAR9           8196
#define ID_VIEW_USER_TOOLBAR10          8197
#define ID_VIEW_WATCH                   8198
#define ID_VIEW_WHITESPACE              8199
#define ID_VIEW_WORKSPACE               8200
#define ID_WINDOW_MANAGER               8201
#define ID_TEAR_OFF1                    8202
#define ID_TEAR_OFF2                    8203
#define ID_TEAR_OFF3                    8204
#define ID_TEAR_OFF4                    8205
#define ID_TEAR_OFF5                    8206
#define ID_TEAR_OFF6                    8207
#define ID_TEAR_OFF7                    8208
#define ID_TEAR_OFF8                    8209
#define ID_TEAR_OFF9                    8210
#define ID_TEAR_OFF10                   8211
#define ID_TEAR_OFF11                   8212
#define ID_TEAR_OFF12                   8213
#define ID_TEAR_OFF13                   8214
#define ID_TEAR_OFF14                   8215
#define ID_TEAR_OFF15                   8216
#define ID_TEAR_OFF16                   8217
#define ID_TEAR_OFF17                   8218
#define ID_TEAR_OFF18                   8219
#define ID_TEAR_OFF19                   8220
#define ID_TEAR_OFF20                   8221
#define ID_TEAR_OFF21                   8222
#define ID_TEAR_OFF22                   8223
#define ID_TEAR_OFF23                   8224
#define ID_TEAR_OFF24                   8225
#define ID_TEAR_OFF25                   8226
#define ID_TEAR_OFF26                   8227
#define ID_TEAR_OFF27                   8228
#define ID_TEAR_OFF28                   8229
#define ID_TEAR_OFF29                   8230
#define ID_EDIT_FIND_COMBO              8231
#define ID_TOOLS_OPTIONS                8232
#define ID_TOOLS_VIEW_KNOWLEDGE_BASE    40002
#define ID_Menu                         40003
#define ID_BUILD_SYNTAXCHECK            40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
